# Generated by Django 2.1.1 on 2018-09-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firest_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('confirm_password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
