# Generated by Django 2.1.1 on 2018-09-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_auto_20180925_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=64),
        ),
    ]
